export const routes = {
 home: ['/', '/en/'], products: ['/produkte/', '/en/products/'], government: ['/government/', '/en/government/'],
 manufacturing: ['/fertigung/', '/en/manufacturing/'], oem: ['/oem-distribution/', '/en/oem-distribution/'],
 contact: ['/kontakt/', '/en/contact/'], legal: ['/impressum/', '/en/legal/'], privacy: ['/datenschutz/', '/en/privacy/']
};
export const t = (lang, de, en) => lang === 'de' ? de : en;
export const esc = str => String(str).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
export const route = (key, lang) => routes[key][lang === 'de' ? 0 : 1];
export const request = (lang, type) => route('contact', lang)+'?type='+type;
export const image = (file, alt, eager = false, focusDuty = false) => {
 const img = `<img src="/assets/${file}" alt="${esc(alt)}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
 return focusDuty ? `<div class="duty-focus">${img}</div>` : img;
};
export const button = (label, href, secondary = false) => `<a class="btn${secondary ? ' btn-secondary' : ''}" href="${esc(href)}">${esc(label)}</a>`;
const intro = (label, title, text, actions = '') => `<section class="page-intro"><div class="shell"><span class="eyebrow">${label}</span><h1 class="page-title">${title}</h1><p class="page-lede">${text}</p>${actions}</div></section>`;
const link = (label, href) => `<a class="text-link" href="${esc(href)}">${esc(label)} ↗</a>`;
const actions = (...buttons) => `<div class="actions">${buttons.join('')}</div>`;
const models = ['Glock 17', 'Glock 34', 'Walther Q5 SF', 'Walther PDP 4″', 'Walther PDP 4,5″', 'Walther PDP 5″', 'SIG Sauer P320', 'CZ Shadow 2', 'Beretta 92FS'];
const compatibility = lang => `<ul class="compatibility-list">${models.map(m => `<li>${esc(lang === 'en' ? m.replace('4,5', '4.5') : m)}</li>`).join('')}<li>Taser 10 · ${t(lang,'Geräteholster','Equipment holster')}</li></ul>`;
const steps = rows => `<div class="steps-grid">${rows.map(([n,h,p])=>`<article class="step"><span class="step-number">${n}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div>`;
const brief = rows => `<div class="procurement-brief">${rows.map(([label,title,text])=>`<div class="brief-item"><span class="eyebrow">${label}</span><strong>${title}</strong><p>${text}</p></div>`).join('')}</div>`;
const cta = (lang, title, text, type='information', label=t(lang,'Kontakt aufnehmen','Get in touch')) => `<section class="shell cta-strip"><div><span class="eyebrow">YOUR NEXT STEP</span><h2>${title}</h2><p>${text}</p></div>${button(label+' ↗',request(lang,type))}</section>`;
const modelNote = lang => `<p class="brief-note">${t(lang,'Die genaue Modellvariante, Ausstattung und Befestigung werden vor dem Auftrag abgestimmt. Abbildungen zeigen Beispielkonfigurationen.','Exact model variant, equipment and mounting are agreed before ordering. Photographs show example configurations.')}</p>`;

const families = lang => `<div class="product-grid">${[
 ['duty-hero.webp','HELLWEG Duty System / Tiger Stripe','01 / DUTY SYSTEMS',t(lang,'Dienstholster & Tragesysteme','Duty holsters & carrying systems'),t(lang,'Waffenmodell, Ausstattung und Befestigung im Zusammenhang betrachten. Für professionelle Anforderungen und Beschaffungsprojekte.','Coordinate the weapon model, equipment and mounting as a system. For professional requirements and procurement projects.'),route('products',lang)+'#duty',t(lang,'Duty-Systeme entdecken','Explore duty systems'),'product-card--duty'],
 ['walther-q5sf.webp','HELLWEG Walther Q5 SF / Tropical','02 / CUSTOM & SPORT',t(lang,'Individuelle Holster','Custom holsters'),t(lang,'Modellgenaue Passform, persönliche Gestaltung. Farben, Muster, Trageseite und Ausführung direkt mit HELLWEG abstimmen.','Model-specific fit and a personal finish. Discuss colours, patterns, carry side and configuration directly with HELLWEG.'),route('products',lang)+'#custom',t(lang,'Gestaltung entdecken','Explore customisation'),''],
 ['magazinhalter-doppelt.jpg',t(lang,'HELLWEG doppelter Magazinhalter','HELLWEG double magazine carrier'),'03 / ACCESSORIES',t(lang,'Magazinhalter','Magazine carriers'),t(lang,'Einfach- und Doppelhalter ergänzen die Ausstattung. Magazinversion, Befestigung und Trageposition bestimmen die passende Ausführung.','Single and double carriers complement your equipment. Magazine version, mounting and carry position define the configuration.'),route('products',lang)+'#accessories',t(lang,'Zubehör ansehen','Explore accessories'),'']
].map(([file,alt,tag,title,text,url,label,cls])=>`<article class="product-card ${cls}">${image(file,alt)}<div class="product-copy"><span class="eyebrow">${tag}</span><h3>${title}</h3><p>${text}</p>${link(label,url)}</div></article>`).join('')}</div>`;

function home(lang) {
 return `<section class="shell hero"><div class="hero-copy"><span class="eyebrow">HOLSTERS / CARRYING SYSTEMS / HELLWEG</span><h1>${t(lang,'Modellgenaue Holster.<br>Für Ihren Einsatz.','Model-specific holsters.<br>For your requirements.')}</h1><p class="lede">${t(lang,'HELLWEG fertigt individuelle Holster und Magazinhalter. Wir stimmen Waffenmodell, Ausstattung, Trageweise und Befestigung persönlich mit Ihnen ab — für professionelle Anwender und individuelle Anforderungen.','HELLWEG manufactures custom holsters and magazine carriers. We work with you to define the weapon model, equipment, carrying position and mounting — for professional users and individual requirements.')}</p>${actions(button('Law Enforcement & Defence ↗',route('government',lang)),button(t(lang,'Produkte entdecken','Explore products'),route('products',lang),true))}<p class="hero-note">${t(lang,'Behörden · Ausrüster · Individuelle Anwender','Government agencies · Equipment suppliers · Individual users')}</p></div><div class="hero-visual product-visual">${image('duty-hero.webp',t(lang,'HELLWEG Duty-Holster in Tiger Stripe mit Haltebügel','HELLWEG duty holster in Tiger Stripe with retaining strap'),true,true)}<span class="image-label">DUTY SYSTEM / TIGER STRIPE<br>${t(lang,'Beispielkonfiguration','Example configuration')}</span></div></section>
 <div class="shell facts-strip"><div class="fact"><strong>${t(lang,'Modellgenau gefertigt','Model-specific fit')}</strong><span>${t(lang,'MODELL · AUSSTATTUNG · TRAGEWEISE','MODEL · EQUIPMENT · CARRY POSITION')}</span></div><div class="fact"><strong>${t(lang,'Persönlich abgestimmt','Direct consultation')}</strong><span>${t(lang,'IHR BEDARF IM MITTELPUNKT','YOUR REQUIREMENTS COME FIRST')}</span></div><div class="fact"><strong>${t(lang,'Ansprechpartner in Europa','European point of contact')}</strong><span>HELLWEG GMBH · DE / EN</span></div></div>
 <section class="section"><div class="shell"><div class="section-heading"><span class="eyebrow">FIND YOUR STARTING POINT</span><h2>${t(lang,'Ihr Bedarf.<br>Ihr direkter Weg.','Your requirements.<br>Your starting point.')}</h2><p>${t(lang,'Vom Beschaffungsprojekt bis zum einzelnen Holster: Finden Sie die Informationen, die für Ihre Anfrage entscheidend sind.','From a procurement project to an individual holster: find the information that matters for your enquiry.')}</p></div><div class="route-cards">${[
 ['01',t(lang,'Behörden & Beschaffung','Government & procurement'),t(lang,'Modellbasis, technische Anforderungen, RFQ und Evaluierung. Für Polizei, Sicherheitsbehörden und öffentliche Beschaffungsstellen.','Model coverage, technical requirements, RFQs and evaluation. For police, security agencies and public procurement teams.'),route('government',lang),t(lang,'Beschaffung erkunden','Explore procurement')],
 ['02',t(lang,'OEM & Vertriebspartner','OEM & distribution partners'),t(lang,'Produktkonfiguration, Zielmarkt und mögliche Zusammenarbeit. Für Ausrüster, Integratoren und Distributoren.','Product configuration, target market and potential collaboration. For equipment suppliers, integrators and distributors.'),route('oem',lang),t(lang,'Partnerprojekt besprechen','Explore partnerships')],
 ['03',t(lang,'Individuell & Sport','Custom & sport'),t(lang,'Passform und Gestaltung für Ihre persönliche Ausstattung. Entdecken Sie Modelle, Farben und Beispielkonfigurationen.','Fit and finish for your individual equipment. Explore models, colours and example configurations.'),route('products',lang)+'#custom',t(lang,'Holster entdecken','Explore holsters')]
 ].map(([n,h,p,url,l])=>`<article class="route-card"><span class="route-icon">${n}</span><h3>${h}</h3><p>${p}</p>${link(l,url)}</article>`).join('')}</div></div></section>
 <section class="section"><div class="shell"><div class="section-heading"><span class="eyebrow">THE PRODUCT FAMILIES</span><h2>${t(lang,'Die Konfiguration beginnt<br>mit Ihrem Modell.','The configuration starts<br>with your model.')}</h2><p>${t(lang,'Dienstholster, individuelle Holster und Magazinhalter — entdecken Sie die Produktfamilien von HELLWEG.','Duty holsters, custom holsters and magazine carriers — discover the HELLWEG product families.')}</p></div>${families(lang)}</div></section>
 <section class="government-band"><div class="shell"><div class="band-copy"><span class="eyebrow">LAW ENFORCEMENT & DEFENCE</span><h2>${t(lang,'Klare Anforderungen.<br>Ein direkter Ansprechpartner.','Defined requirements.<br>A direct point of contact.')}</h2><p>${t(lang,'Bei einer Beschaffung zählt die konkrete Ausführung. Besprechen Sie Modell, Schnittstellen, Sicherung und Projektplanung mit Daniel Hellweg.','Procurement depends on the exact configuration. Discuss your model, interfaces, retention requirements and project planning with Daniel Hellweg.')}</p>${actions(button(t(lang,'Beschaffungsprojekt besprechen','Discuss a procurement project')+' ↗',request(lang,'rfq')),link(t(lang,'Zum Behördenbereich','Explore government procurement'),route('government',lang)))}</div><div class="band-aside"><ul class="audience-list"><li>${t(lang,'Polizei & Bundespolizei','Police & law enforcement')}</li><li>${t(lang,'Zoll & Grenzschutz','Customs & border protection')}</li><li>${t(lang,'Defence & öffentliche Beschaffung','Defence & public procurement')}</li><li>${t(lang,'Justizvollzug & Sicherheitsbehörden','Corrections & security agencies')}</li><li>${t(lang,'Ausrüster & Systemlieferanten','Equipment suppliers & integrators')}</li></ul></div></div></section>
 <section class="section"><div class="shell split-grid"><div class="content-copy"><span class="eyebrow">INDIVIDUAL MANUFACTURING</span><h2>${t(lang,'Nicht von der Stange.<br>Für Ihre Ausstattung.','Not off the shelf.<br>For your equipment.')}</h2><p>${t(lang,'Optik, Licht, Trageseite und Befestigung entscheiden über die Konfiguration. Wir klären diese Details persönlich, damit Ihre Anfrage auf einer präzisen Grundlage steht.','Optics, lights, carry side and mounting define the configuration. We clarify these details personally so your enquiry starts from a precise specification.')}</p>${link(t(lang,'Fertigung & Unternehmen kennenlernen','Discover manufacturing & company'),route('manufacturing',lang))}</div><div class="spec-table"><dl><dt>${t(lang,'Unternehmen','Company')}</dt><dd>Hellweg GmbH</dd><dt>${t(lang,'Ansprechpartner','Contact')}</dt><dd>Daniel Hellweg</dd><dt>${t(lang,'Unternehmenssitz','Registered office')}</dt><dd>Lohmar, Germany</dd><dt>${t(lang,'Abstimmung','Consultation')}</dt><dd>${t(lang,'Modell · Zubehör · Tragesystem','Model · accessories · carrying system')}</dd></dl></div></div></section>
 ${cta(lang,t(lang,'Was muss Ihr Holster leisten?','What does your holster need to do?'),t(lang,'Beschreiben Sie Ihre Ausstattung und Ihren Bedarf. Den nächsten Schritt stimmen wir direkt mit Ihnen ab.','Describe your equipment and requirements. We will discuss the next step directly with you.'))}`;
}

function government(lang) {
 return intro('LAW ENFORCEMENT / DEFENCE / GOVERNMENT',t(lang,'Klare Anforderungen.<br>Die passende Konfiguration.','Defined requirements.<br>The right configuration.'),t(lang,'Holster- und Tragesysteme für Polizei, Behörden und Ausrüstungspartner. Besprechen Sie Waffenmodell, Ausstattung und Beschaffungsbedarf direkt mit HELLWEG.','Holsters and carrying systems for law enforcement, government agencies and equipment partners. Discuss your weapon model, equipment and procurement requirements directly with HELLWEG.'),actions(button(t(lang,'Beschaffungsprojekt besprechen','Discuss a procurement project'),request(lang,'rfq')),button(t(lang,'Technische Informationen anfragen','Request technical information'),request(lang,'technical'),true)))+
 `<section class="shell content-section"><div class="split-grid"><div class="content-copy"><span class="eyebrow">YOUR DIRECT POINT OF CONTACT</span><h2>${t(lang,'Ihre Anforderungen.<br>Unsere Gesprächsgrundlage.','Your requirements.<br>Our starting point.')}</h2><p>${t(lang,'Die Hellweg GmbH mit Sitz in Lohmar verbindet individuelle Holsterfertigung mit persönlicher Projektabstimmung. Daniel Hellweg ist Ihr Ansprechpartner für Produktkonfigurationen, technische Anforderungen und Beschaffungsanfragen.','Based in Lohmar, Hellweg GmbH combines individual holster manufacturing with direct project consultation. Daniel Hellweg is your point of contact for product configurations, technical requirements and procurement enquiries.')}</p><p>${t(lang,'Für Polizei, Bundespolizei, Zoll, Grenzschutz, Justizvollzug und Defence-Beschaffungsstellen: Das konkrete Lastenheft bestimmt, welche Ausführung geprüft werden muss.','For police, customs, border protection, corrections and defence procurement teams: your specification determines the exact configuration to be assessed.')}</p>${link(t(lang,'Unternehmen kennenlernen','About the company'),route('manufacturing',lang))}</div><div class="image-frame product-visual">${image('duty-hero.webp',t(lang,'HELLWEG Duty-Tragesystem, Beispielkonfiguration','HELLWEG duty carrying system, example configuration'))}</div></div></section>
 <section class="shell content-section"><span class="eyebrow">PRODUCT / SPECIFICATION / PROCUREMENT</span><h2>${t(lang,'Drei Ebenen.<br>Eine konkrete Anfrage.','Three levels.<br>One focused enquiry.')}</h2>${steps([
 ['01 / PRODUCT',t(lang,'Dienstholster & Tragesysteme','Duty holsters & carrying systems'),t(lang,'Besprechen Sie die passende Ausführung für Waffenmodell, Optik, Licht und Befestigung. Duty-Konfigurationen und Magazinhalter geben einen ersten Überblick.','Discuss the configuration for your weapon model, optic, light and mounting. Duty configurations and magazine carriers provide an initial overview.')],
 ['02 / SPECIFICATION',t(lang,'Technische Anforderungen','Technical requirements'),t(lang,'Beschreiben Sie Sicherung, Ziehablauf, Trageweise und Schnittstellen. Ihr Lastenheft bildet die Grundlage für die Prüfung der konkreten Konfiguration.','Describe retention, draw requirements, carrying position and interfaces. Your specification provides the basis for assessing the exact configuration.')],
 ['03 / PLANNING',t(lang,'Mengen & Projektplanung','Quantities & project planning'),t(lang,'Nennen Sie Stückzahl, Termin und geplante Abrufe. Lieferplanung, Musterbedarf und Nachversorgung werden für das jeweilige Projekt geklärt.','Include quantities, timelines and planned call-off orders. Delivery planning, sample requirements and replenishment are addressed for each project.')]
 ])}</section>
 <section class="shell content-section"><span class="eyebrow">MODEL COVERAGE</span><h2>${t(lang,'Vorhandene Modelle.<br>Präzise abgestimmt.','Existing models.<br>Precisely configured.')}</h2><p>${t(lang,'HELLWEG fertigt bereits für die folgenden Modelle. Geben Sie die genaue Variante sowie Optik, Licht und Befestigung bei Ihrer Anfrage an.','HELLWEG already manufactures for the following models. Include the exact variant, optic, light and mounting in your enquiry.')}</p>${compatibility(lang)}${modelNote(lang)}${link(t(lang,'Produkte & Beispiele ansehen','View products & examples'),route('products',lang))}</section>
 <section class="government-band"><div class="shell"><div class="band-copy"><span class="eyebrow">RFQ / RFI / EVALUATION</span><h2>${t(lang,'Von Ihrem Lastenheft<br>zum Projektgespräch.','From your specification<br>to a project discussion.')}</h2><p>${t(lang,'Ob erste Marktsondierung oder konkrete Ausschreibung: Teilen Sie die relevanten Eckdaten. Muster, technische Dokumentation und Lieferbedingungen werden anforderungsspezifisch geklärt.','Whether you are researching the market or preparing a tender, share the relevant details. Samples, technical documentation and delivery terms are addressed against your requirements.')}</p>${actions(button(t(lang,'RFQ / RFI anfragen','Submit an RFQ / RFI'),request(lang,'rfq')),button(t(lang,'Musterverfügbarkeit klären','Discuss sample availability'),request(lang,'samples'),true))}</div><div class="band-aside"><ul class="audience-list"><li>${t(lang,'Organisation & Land','Organisation & country')}</li><li>${t(lang,'Waffenmodell & Ausstattung','Weapon model & equipment')}</li><li>${t(lang,'Stückzahl & Evaluierungszeitraum','Quantity & evaluation period')}</li><li>${t(lang,'Lastenheft & Referenznummer','Specification & tender reference')}</li></ul></div></div></section>
 <section class="shell content-section"><span class="eyebrow">A CLEAR TECHNICAL BRIEF</span><h2>${t(lang,'Was wir gemeinsam klären.','What we clarify together.')}</h2>${brief([
 ['01',t(lang,'Passform','Fit'),t(lang,'Modell, Generation, Lauflänge, Optik und Licht.','Model, generation, barrel length, optic and light.')],
 ['02',t(lang,'Sicherung','Retention'),t(lang,'Vorgesehene Nutzung, geforderte Level, Normen und Prüfunterlagen.','Intended use, required levels, standards and test documentation.')],
 ['03',t(lang,'Integration','Integration'),t(lang,'Trageposition, Befestigung und Schnittstellen Ihrer Ausstattung.','Carry position, mounting and equipment interfaces.')],
 ['04',t(lang,'Beschaffung','Procurement'),t(lang,'Mengen, Termine, Evaluierung und Anforderungen an Nachversorgung.','Quantities, timelines, evaluation and replenishment requirements.')]
 ])}</section>
 <section class="shell content-section"><span class="eyebrow">PROCUREMENT QUESTIONS</span><h2>${t(lang,'Vor dem ersten Gespräch.','Before the first discussion.')}</h2><div class="faq-list">${[
 [t(lang,'Welche Angaben helfen bei einer Ausschreibungsanfrage?','What should a tender enquiry include?'),t(lang,'Organisation, Waffen- oder Gerätemodell, Ausstattung, Stückzahl, Referenznummer und Termin. Ergänzen Sie technische Anforderungen und das Lastenheft, sofern vorhanden.','Your organisation, weapon or equipment model, configuration, quantity, reference number and timeline. Include technical requirements and your specification where available.')],
 [t(lang,'Wie werden Sicherung und technische Eignung geklärt?','How are retention and technical suitability assessed?'),t(lang,'Nennen Sie den vorgesehenen Einsatz sowie geforderte Retention-Level, Normen und Prüfunterlagen. So kann die betreffende Konfiguration gezielt geprüft werden.','Specify the intended use and any required retention levels, standards and test documentation so the relevant configuration can be assessed.')],
 [t(lang,'Wie bespreche ich Muster und Lieferplanung?','How do I discuss samples and delivery planning?'),t(lang,'Geben Sie Ihren Evaluierungszeitraum und die geplante Menge an. Verfügbarkeit, Ausführung und Lieferbedingungen werden im Projektgespräch geklärt.','Include your evaluation period and planned quantity. Availability, configuration and delivery terms are clarified during the project discussion.')]
 ].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>
 ${cta(lang,t(lang,'Sie planen eine Beschaffung?','Planning a procurement project?'),t(lang,'Sprechen Sie direkt mit Daniel Hellweg über Ihren Bedarf.','Discuss your requirements directly with Daniel Hellweg.'),'rfq',t(lang,'Projekt anfragen','Enquire about your project'))}`;
}

function products(lang) {
 return intro('PRODUCTS / MODEL-SPECIFIC SYSTEMS',t(lang,'Ihr Modell.<br>Ihre Konfiguration.','Your model.<br>Your configuration.'),t(lang,'Dienstsysteme, individuelle Holster und Magazinhalter. Entdecken Sie die Produktfamilien — und stimmen Sie Ihre genaue Ausstattung persönlich mit uns ab.','Duty systems, custom holsters and magazine carriers. Explore the product families — and discuss your exact equipment with us.'),actions(button(t(lang,'Modell besprechen','Discuss your model'),request(lang,'custom')),button(t(lang,'Zur Modellübersicht','View model coverage'),'#models',true)))+
 `<section class="shell content-section">${families(lang)}</section>
 <section class="shell content-section" id="duty"><div class="product-detail"><div class="image-frame product-visual">${image('duty-hero.webp','HELLWEG Duty System / Tiger Stripe')}</div><div class="content-copy"><span class="eyebrow">DUTY SYSTEMS</span><h2>${t(lang,'Das Holster als<br>Teil Ihrer Ausstattung.','The holster as part<br>of your equipment.')}</h2><p>${t(lang,'Für Dienstanforderungen zählen Modell, Sicherung und Befestigung zusammen. Beschreiben Sie Ihren vorgesehenen Einsatz und Ihre Schnittstellen — wir besprechen die konkrete Ausführung.','For duty requirements, the model, retention and mounting matter together. Describe your intended use and interfaces — we will discuss the exact configuration.')}</p><dl class="spec-table"><dt>${t(lang,'Konfiguration','Configuration')}</dt><dd>${t(lang,'Modell · Optik · Licht','Model · optic · light')}</dd><dt>${t(lang,'Tragesystem','Carrying system')}</dt><dd>${t(lang,'Position · Befestigung · Trageseite','Position · mounting · carry side')}</dd><dt>${t(lang,'Prüfung','Assessment')}</dt><dd>${t(lang,'Technische Vorgaben im Projekt klären','Discuss technical specifications per project')}</dd></dl>${link(t(lang,'Technische Informationen anfragen','Request technical information'),request(lang,'technical'))}</div></div></section>
 <section class="shell content-section" id="models"><span class="eyebrow">MODEL COVERAGE</span><h2>${t(lang,'Für diese Modelle<br>fertigt HELLWEG bereits.','HELLWEG already manufactures<br>for these models.')}</h2>${compatibility(lang)}<p>${t(lang,'Weitere Modelle besprechen wir gern auf Anfrage. Nennen Sie bitte die genaue Variante und Ihre Ausstattung.','Discuss additional models with us on request. Include the exact variant and your equipment.')}</p>${modelNote(lang)}${button(t(lang,'Mein Modell anfragen','Enquire about my model'),request(lang,'custom'))}</section>
 <section class="shell content-section" id="custom"><div class="section-heading"><span class="eyebrow">CUSTOM / SPORT / INDIVIDUAL</span><h2>${t(lang,'Passform mit<br>persönlicher Handschrift.','Model-specific fit.<br>A personal signature.')}</h2><p>${t(lang,'Unifarben, Camouflage oder ein individuelles Muster: Gestalten Sie die Ausführung gemeinsam mit HELLWEG. Farben, Trageseite und Befestigung werden persönlich abgestimmt.','Solid colours, camouflage or a distinctive pattern: define your configuration with HELLWEG. Colours, carry side and mounting are coordinated personally.')}</p></div><div class="model-gallery">${[
 ['walther-q5sf.webp','Walther Q5 SF','Tropical'],['cz-shadow2.webp','CZ Shadow 2','Floral Skull'],['taser10.webp','Taser 10',t(lang,'Neon Gelb · Geräteholster','Neon yellow · equipment holster')]
 ].map(([f,h,p])=>`<article class="model-card">${image(f,'HELLWEG '+h+' / '+p)}<span class="eyebrow">EXAMPLE CONFIGURATION</span><h3>${h}</h3><p>${p}</p>${link(t(lang,'Konfiguration besprechen','Discuss this configuration'),request(lang,h==='Taser 10'?'technical':'custom')+'&model='+encodeURIComponent(h))}</article>`).join('')}</div>${modelNote(lang)}</section>
 <section class="shell content-section" id="accessories"><div class="product-detail"><div class="image-frame">${image('magazinhalter-doppelt.jpg',t(lang,'HELLWEG Doppel-Magazinhalter für Glock / SIG Sauer P320, Beispiel','HELLWEG double magazine carrier for Glock / SIG Sauer P320, example'))}</div><div class="content-copy"><span class="eyebrow">MAGAZINE CARRIERS</span><h2>${t(lang,'Ihre Ausstattung.<br>Konsequent ergänzt.','Your equipment.<br>A considered addition.')}</h2><p>${t(lang,'Einfach- und Doppelhalter vervollständigen Ihr Tragesystem. Beispiele umfassen einen Einfachhalter für Beretta 92FS und einen Doppelhalter für Glock / SIG Sauer P320.','Single and double carriers complete your carrying system. Examples include a single carrier for Beretta 92FS and a double carrier for Glock / SIG Sauer P320.')}</p><p>${t(lang,'Magazinversion, genaue Modellvariante, Trageseite und Befestigung klären wir mit Ihnen vor dem Auftrag.','Magazine version, exact model variant, carry side and mounting are agreed with you before ordering.')}</p>${link(t(lang,'Magazinhalter anfragen','Enquire about magazine carriers'),request(lang,'custom'))}</div></div></section>
 ${cta(lang,t(lang,'Eine Idee für Ihr Holster?','Have a configuration in mind?'),t(lang,'Teilen Sie Modell, Ausstattung und Gestaltungswünsche. Wir besprechen Ihre individuelle Ausführung.','Share your model, equipment and preferred finish. We will discuss your custom configuration.'),'custom',t(lang,'Individuelles Holster anfragen','Enquire about a custom holster'))}`;
}

function manufacturing(lang) {
 return intro('MANUFACTURING / COMPANY',t(lang,'Individuell gefertigt.<br>Persönlich verbunden.','Individually manufactured.<br>Personally connected.'),t(lang,'Modellgenaue Holster, persönliche Abstimmung und eine Familientradition mit australischen Wurzeln. Lernen Sie HELLWEG in Europa kennen.','Model-specific holsters, direct consultation and a family tradition with Australian roots. Discover HELLWEG in Europe.'))+
 `<section class="shell content-section"><div class="split-grid"><div class="content-copy"><span class="eyebrow">CONFIGURATION BEFORE PRODUCTION</span><h2>${t(lang,'Die Details machen<br>die Konfiguration.','The details define<br>the configuration.')}</h2><p>${t(lang,'Waffenmodell, Ausstattung und Trageweise bestimmen die Ausführung. Wir stimmen Passform, Halteverhalten, Gestaltung und Befestigung persönlich mit Ihnen ab.','Weapon model, equipment and carrying position define the configuration. We work with you to coordinate fit, retention, finish and mounting.')}</p><p>${t(lang,'Für professionelle Beschaffungen nehmen wir zusätzlich die geforderten technischen Nachweise und Projektbedingungen auf. Die Ausführung und Bedingungen werden vor dem Auftrag geklärt.','For professional procurement, we also consider the technical documentation and project conditions you require. Configuration and terms are clarified before ordering.')}</p></div><div class="spec-table"><dl><dt>${t(lang,'Modell','Model')}</dt><dd>${t(lang,'Variante · Generation · Ausstattung','Variant · generation · equipment')}</dd><dt>${t(lang,'Nutzung','Use')}</dt><dd>${t(lang,'Dienst · Sport · Individuelle Anforderung','Duty · sport · individual requirement')}</dd><dt>${t(lang,'Gestaltung','Customisation')}</dt><dd>${t(lang,'Farbe · Muster · Trageseite','Colour · pattern · carry side')}</dd><dt>${t(lang,'Integration','Integration')}</dt><dd>${t(lang,'Befestigung · Schnittstellen','Mounting · interfaces')}</dd></dl></div></div></section>
 <section class="shell content-section"><span class="eyebrow">FROM REQUIREMENT TO CONFIGURATION</span><h2>${t(lang,'Ein klarer Weg<br>zu Ihrer Anfrage.','A clear path<br>to your enquiry.')}</h2>${steps([
 ['01 / DEFINE',t(lang,'Bedarf beschreiben','Define your requirements'),t(lang,'Modell, Ausstattung, Einsatzzweck und Gestaltungswünsche nennen.','Include your model, equipment, intended use and preferred finish.')],
 ['02 / COORDINATE',t(lang,'Ausführung abstimmen','Coordinate the configuration'),t(lang,'Passform, Sicherung, Befestigung und technische Anforderungen besprechen.','Discuss fit, retention, mounting and technical requirements.')],
 ['03 / CONFIRM',t(lang,'Projektbasis klären','Confirm the project basis'),t(lang,'Verfügbarkeit, Dokumentation, Termine und kaufmännische Bedingungen vor dem Auftrag klären.','Clarify availability, documentation, timelines and commercial terms before ordering.')]
 ])}</section>
 <section class="shell content-section"><div class="split-grid"><div class="content-copy"><span class="eyebrow">THE FAMILY TRADITION</span><h2>${t(lang,'Wurzeln in Australien.<br>Fortführung in Europa.','Roots in Australia.<br>Continued in Europe.')}</h2><p>${t(lang,'Die Familientradition beginnt 1979 in Melbourne mit der Gründung von Hellweg Australia durch Albert Hellweg. Daniel Hellweg führt diese Tradition in Europa mit individueller Holsterfertigung fort.','The family tradition began in Melbourne in 1979 when Albert Hellweg founded Hellweg Australia. Daniel Hellweg continues that tradition in Europe through individual holster manufacturing.')}</p><p>${t(lang,'Heute ist die Hellweg GmbH mit Sitz in Lohmar Ihr direkter Ansprechpartner für Produktkonfigurationen und Projektanfragen.','Today, Hellweg GmbH, based in Lohmar, is your direct point of contact for product configurations and project enquiries.')}</p>${link(t(lang,'Kontakt zu Daniel Hellweg','Contact Daniel Hellweg'),route('contact',lang))}</div><div class="image-frame">${image('daniel-benjamin-together.jpg',t(lang,'Daniel und Benjamin Hellweg','Daniel and Benjamin Hellweg'))}</div></div></section>
 ${cta(lang,t(lang,'Ihre Anforderungen sind der Anfang.','Your requirements are the starting point.'),t(lang,'Beschreiben Sie die Ausstattung, die Ihnen wichtig ist. Wir klären die nächsten Schritte mit Ihnen.','Describe the equipment that matters to you. We will discuss the next steps with you.'))}`;
}

function oem(lang) {
 return intro('PARTNERS / OEM / DISTRIBUTION',t(lang,'Holstersysteme.<br>Gemeinsam weiterdenken.','Holster systems.<br>Explore the possibilities together.'),t(lang,'Für Polizeiausrüster, Systemlieferanten und Distributoren: Besprechen Sie Ihre Produktanforderungen, Ihren Zielmarkt und eine mögliche Zusammenarbeit direkt mit HELLWEG.','For police equipment suppliers, system integrators and distributors: discuss your product requirements, target market and potential collaboration directly with HELLWEG.'),actions(button(t(lang,'Partnerprojekt besprechen','Discuss a partnership'),request(lang,'partner'))))+
 `<section class="shell content-section">${steps([
 ['01 / EQUIPMENT PARTNERS',t(lang,'Ausrüster & Systemlieferanten','Equipment suppliers & integrators'),t(lang,'Abstimmung von Produktkonfiguration, Befestigung und Kundenvorgaben. Beschreiben Sie, wie das Holster in Ihr Ausrüstungsangebot integriert werden soll.','Coordinate product configuration, mounting and customer requirements. Describe how the holster should fit into your equipment offering.')],
 ['02 / OEM & PRIVATE LABEL',t(lang,'Projektmöglichkeiten prüfen','Explore project possibilities'),t(lang,'Bringen Sie Anforderungen an Ausführung, Kennzeichnung, Verpackung und geplante Mengen ein. Gemeinsam wird geklärt, welche Projektform geeignet ist.','Share your requirements for configuration, branding, packaging and planned quantities. Discuss which project arrangement could be suitable.')],
 ['03 / DISTRIBUTION',t(lang,'Zielmarkt & Vertrieb','Target market & distribution'),t(lang,'Nennen Sie Zielmarkt, Vertriebskanal und Produktbedarf. Wir besprechen die Voraussetzungen einer Zusammenarbeit und die Anforderungen Ihres Marktes.','Specify your target market, sales channel and product requirements. Discuss the basis for collaboration and the requirements of your market.')]
 ])}</section>
 <section class="shell content-section"><span class="eyebrow">A USEFUL FIRST DISCUSSION</span><h2>${t(lang,'Ihr Partnerprojekt.<br>Klar beschrieben.','Your partnership project.<br>Clearly defined.')}</h2>${brief([
 ['01',t(lang,'Unternehmen & Markt','Company & market'),t(lang,'Organisation, Land, Zielmarkt und Vertriebskanal.','Organisation, country, target market and sales channel.')],
 ['02',t(lang,'Produkt & Integration','Product & integration'),t(lang,'Produktfamilie, Modellkonfiguration und Schnittstellen.','Product family, model configuration and interfaces.')],
 ['03',t(lang,'Umfang & Termine','Scope & timelines'),t(lang,'Geplante Mengen, Projektzeitraum und mögliche Abrufe.','Planned quantities, project timeline and potential call-off orders.')],
 ['04',t(lang,'Zusammenarbeit','Collaboration'),t(lang,'Branding, Dokumentation sowie technische und regulatorische Vorgaben.','Branding, documentation and technical or regulatory requirements.')]
 ])}</section>
 ${cta(lang,t(lang,'Lassen Sie uns Ihr Vorhaben besprechen.','Let’s discuss your project.'),t(lang,'Ein direkter Einstieg — ohne pauschale Partnerbedingungen. Beschreiben Sie Ihr Markt- und Produktziel.','A direct starting point, with terms discussed per project. Describe your market and product objectives.'),'partner',t(lang,'Partneranfrage stellen','Submit a partner enquiry'))}`;
}

function contact(lang, { preview }) {
 const options = [['information',t(lang,'Allgemeine Anfrage / Beschaffungsinformationen','General enquiry / procurement information')],['rfq','Ausschreibung / RFQ / RFI'],['technical',t(lang,'Technische Dokumentation','Technical documentation')],['samples',t(lang,'Musterverfügbarkeit','Sample availability')],['partner','OEM / Distribution'],['custom',t(lang,'Individuelles Holster / Sport','Custom holster / sport')]];
 const fields = [['name',t(lang,'Ansprechpartner','Contact person'),'text',true,'name'],['email',t(lang,'E-Mail','Email'),'email',true,'email'],['organisation',t(lang,'Organisation / Unternehmen','Organisation / company'),'text',false,'organization'],['country',t(lang,'Land','Country'),'text',false,'country-name'],['phone',t(lang,'Telefon','Phone'),'tel',false,'tel'],['product',t(lang,'Benötigtes Produkt','Product required'),'text',false,'off'],['model',t(lang,'Waffen- / Gerätemodell inkl. Variante','Weapon / equipment model incl. variant'),'text',false,'off'],['quantity',t(lang,'Erwartete Stückzahl','Expected quantity'),'number',false,'off'],['reference',t(lang,'Ausschreibungs- / RFQ-Nummer','Tender / RFQ reference'),'text',false,'off'],['delivery',t(lang,'Gewünschter Liefertermin','Requested delivery date'),'date',false,'off']];
 const input = ([name,label,type,required,complete]) => `<div class="field"><label for="${name}">${label}${required?' *':''}</label><input id="${name}" name="${name}" type="${type}"${required?' required':''} autocomplete="${complete}"${type==='number'?' min="1" max="100000000" step="1"':type==='date'?'':' maxlength="180"'}></div>`;
 return intro('CONTACT / RFQ / INDIVIDUAL ENQUIRY',t(lang,'Ihr Projekt<br>beginnt hier.','Start your<br>project here.'),t(lang,'Beschaffungsbedarf, Partnerprojekt oder individuelle Konfiguration: Beschreiben Sie Ihre Anforderungen. Daniel Hellweg ist Ihr direkter Ansprechpartner.','Procurement requirements, a partnership or a custom configuration: describe your needs. Daniel Hellweg is your direct point of contact.'))+
 `<section class="shell content-section inquiry-card"><div class="contact-person"><span class="eyebrow">YOUR DIRECT CONTACT</span><h2>Daniel Hellweg</h2><p>Hellweg GmbH · Lohmar, Germany</p></div><div><a class="contact-email" href="mailto:info@hellweg.eu">info@hellweg.eu ↗</a><p>${t(lang,'Direkt per E-Mail oder über das Anfrageformular.','Contact us directly by email or use the enquiry form.')}</p>${button(t(lang,'E-Mail schreiben','Email us'),'mailto:info@hellweg.eu')}</div></section>
 <section class="shell content-section"><span class="eyebrow">WHAT BRINGS YOU TO HELLWEG?</span><div class="intent-grid">${[
 ['rfq',t(lang,'Beschaffung & Behörden','Government & procurement'),t(lang,'RFQ, technische Anforderungen oder Musterbedarf.','RFQ, technical requirements or sample enquiries.')],
 ['partner',t(lang,'OEM & Distribution','OEM & distribution'),t(lang,'Produktbedarf, Zielmarkt und Partnerprojekt.','Product requirements, target market and partnership.')],
 ['custom',t(lang,'Individuell & Sport','Custom & sport'),t(lang,'Ihr Modell, Ihre Ausstattung und Ihre Gestaltung.','Your model, your equipment and your preferred finish.')]
 ].map(([value,title,text])=>`<a class="intent-card" href="${request(lang,value)}#rfq-form" data-intent="${value}"><h3>${title} ↗</h3><p>${text}</p></a>`).join('')}</div></section>
 <section class="shell request-layout form-section"><aside class="request-info"><span class="eyebrow">A FOCUSED FIRST ENQUIRY</span><h2>${t(lang,'So viel wie nötig.<br>So konkret wie möglich.','As much as needed.<br>As precise as possible.')}</h2><p>${t(lang,'Für den ersten Kontakt genügen Name, E-Mail und eine Beschreibung. Weitere Angaben helfen uns, Ihr Vorhaben einzuordnen.','For the first contact, your name, email and a description are enough. Additional details help us understand your project.')}</p><ul><li>${t(lang,'Waffenmodell, Optik und Licht','Weapon model, optic and light')}</li><li>${t(lang,'Tragesystem und Befestigung','Carrying system and mounting')}</li><li>${t(lang,'Stückzahl und gewünschter Termin','Quantity and requested timeline')}</li><li>${t(lang,'Lastenheft oder Referenznummer','Specification or reference number')}</li></ul><p class="brief-note">${t(lang,'Bitte keine vertraulichen oder sicherheitskritischen Unterlagen ohne vorherige Abstimmung übermitteln.','Please do not share confidential or security-sensitive documentation without prior coordination.')}</p>${preview?`<div class="notice">${t(lang,'Vorschau: Der Versand ist erst nach Einrichtung des Maildienstes in Railway verfügbar. Es werden keine Anfragen simuliert oder als zugestellt ausgegeben.','Preview: delivery requires the mail service to be configured in Railway. No enquiries are simulated or reported as delivered.')}</div>`:''}</aside>
 <form id="rfq-form" data-lang="${lang}" action="/api/contact" method="post" enctype="multipart/form-data"><input type="hidden" name="lang" value="${lang}"><div class="form-grid"><div class="field field-wide"><label for="type">${t(lang,'Art der Anfrage','Enquiry type')} *</label><select id="type" name="type" required>${options.map(([value,label])=>`<option value="${value}">${esc(value==='rfq'?t(lang,'Ausschreibung / RFQ / RFI','Tender / RFQ / RFI'):label)}</option>`).join('')}</select></div>${fields.slice(0,2).map(input).join('')}<div class="field field-wide"><label for="message">${t(lang,'Ihre Anforderungen','Your requirements')} *</label><textarea id="message" name="message" required maxlength="5000" placeholder="${t(lang,'Welches Modell und welche Ausstattung benötigen Sie? Was ist für Ihr Projekt wichtig?','Which model and equipment do you need? What matters for your project?')}"></textarea></div></div>
 <details class="structured-enquiry"><summary>${t(lang,'Weitere Produkt- und Projektdetails ergänzen','Add product & project details')}</summary><div class="form-grid">${fields.slice(2).map(input).join('')}<div class="field"><label for="tender">${t(lang,'Ausschreibung / RFQ vorhanden?','Existing tender / RFQ?')}</label><select id="tender" name="tender"><option value="no">${t(lang,'Nein','No')}</option><option value="yes">${t(lang,'Ja','Yes')}</option></select></div></div></details>
 <div class="field field-wide"><label for="documents">${t(lang,'Unterlagen anhängen (optional)','Attach documents (optional)')}</label><input id="documents" name="documents" type="file" accept=".pdf,.jpg,.jpeg,.png,.docx" multiple aria-describedby="document-help"><small id="document-help">${t(lang,'Bis zu 3 Dateien · PDF, JPG, PNG, DOCX · maximal 5 MB je Datei, insgesamt 10 MB.','Up to 3 files · PDF, JPG, PNG, DOCX · maximum 5 MB per file, 10 MB total.')}</small></div>
 <div class="honeypot" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div>
 <p class="help">${t(lang,'* Pflichtfeld. Die Angaben werden zur Bearbeitung Ihrer Anfrage verwendet.','* Required field. The information is used to handle your enquiry.')} <a href="${route('privacy',lang)}">${t(lang,'Datenschutzhinweise','Privacy information')}</a></p><button class="btn" type="submit">${t(lang,'Anfrage senden','Send enquiry')} ↗</button><p class="form-status" role="status" aria-live="polite" tabindex="-1"></p><noscript><p class="notice">${t(lang,'Bitte schreiben Sie direkt an','Please email us directly at')} <a href="mailto:info@hellweg.eu">info@hellweg.eu</a>.</p></noscript></form></section>`;
}

function legal(lang, { preview }) {
 return intro('LEGAL INFORMATION',t(lang,'Impressum','Legal notice'),t(lang,'Anbieterkennzeichnung der Hellweg GmbH.','Company information for Hellweg GmbH.'))+`<section class="shell content-section legal-content"><h2>Hellweg GmbH</h2><p>Auelsweg 22<br>53797 Lohmar<br>${t(lang,'Deutschland','Germany')}</p><h3>${t(lang,'Vertreten durch','Represented by')}</h3><p>${t(lang,'Geschäftsführer: Daniel Hellweg','Managing Director: Daniel Hellweg')}</p><h3>${t(lang,'Kontakt','Contact')}</h3><p><a href="mailto:info@hellweg.eu">info@hellweg.eu</a></p><h3>${t(lang,'Registereintrag','Commercial register')}</h3><p>${t(lang,'Amtsgericht Siegburg','District Court of Siegburg')}<br>HRB 18915</p><h3>${t(lang,'Markenhinweis','Trademark notice')}</h3><p>${t(lang,'Hellweg® ist eine eingetragene Marke. Genannte Hersteller- und Produktnamen dienen der Modellzuordnung. Ihre Nennung impliziert keine Zusammenarbeit oder Freigabe durch die jeweiligen Markeninhaber.','Hellweg® is a registered trademark. Manufacturer and product names identify models. Their inclusion does not imply a partnership or approval by the respective trademark owners.')}</p>${preview?`<div class="notice">${t(lang,'Vor Veröffentlichung: Unternehmensangaben bitte auf Aktualität und Vollständigkeit prüfen.','Before publication: please confirm that company details are current and complete.')}</div>`:''}</section>`;
}

function privacy(lang, { preview }) {
 return intro('PRIVACY / DATA PROTECTION',t(lang,'Datenschutz.','Privacy.'),t(lang,'Informationen zum Websitebesuch und zur Verarbeitung Ihrer Kontaktanfrage.','Information about website access and the handling of your contact enquiry.'))+
 `<section class="shell content-section legal-content">${preview?`<div class="notice">${t(lang,'Freigabe-Entwurf: Vor öffentlicher Veröffentlichung müssen die tatsächlich eingesetzten Hosting- und Mailanbieter, Auftragsverarbeitung, Übermittlungen und Aufbewahrungsregeln bestätigt werden.','Review draft: before public launch, confirm the actual hosting and email providers, processing agreements, transfers and retention rules.')}</div>`:''}
 <h2>${t(lang,'Verantwortlicher','Controller')}</h2><p>Hellweg GmbH<br>Auelsweg 22 · 53797 Lohmar · Germany<br><a href="mailto:info@hellweg.eu">info@hellweg.eu</a></p>
 <h2>${t(lang,'Kontaktanfragen','Contact enquiries')}</h2><p>${t(lang,'Wenn Sie uns eine Anfrage senden, verarbeiten wir Ihre Kontaktdaten, Nachricht und freiwillig ergänzten Projektangaben, um Ihr Anliegen zu bearbeiten. Übermittelte Anhänge werden per E-Mail an HELLWEG weitergeleitet. Die Anwendung legt keine dauerhafte Kopie der Anfrage oder Anhänge in einer eigenen Datenbank ab.','When you send an enquiry, we process your contact details, message and optional project information to handle your request. Submitted attachments are forwarded to HELLWEG by email. The application does not retain a permanent copy of enquiries or attachments in its own database.')}</p><p>${t(lang,'Bei vertragsbezogenen Anfragen erfolgt die Verarbeitung zur Durchführung vorvertraglicher Maßnahmen beziehungsweise eines Vertrags (Art. 6 Abs. 1 lit. b DSGVO). Bei anderen Anfragen erfolgt sie auf Grundlage des berechtigten Interesses an der Bearbeitung Ihrer Anfrage (Art. 6 Abs. 1 lit. f DSGVO). Pflichtangaben sind Name, E-Mail und Nachricht; ohne diese Angaben kann das Formular Ihre Anfrage nicht übermitteln.','Contract-related enquiries are processed for pre-contractual steps or performance of a contract (Article 6(1)(b) GDPR). Other enquiries are processed on the basis of the legitimate interest in handling your request (Article 6(1)(f) GDPR). Name, email and message are required to submit an enquiry through the form.')}</p>
 <h2>${t(lang,'Hosting und technischer Schutz','Hosting and technical protection')}</h2><p>${t(lang,'Die Website wird bei Railway Corporation, USA, in der konfigurierten Region EU West (Amsterdam, Niederlande) betrieben. Beim Zugriff können technische Verbindungsdaten wie IP-Adresse, Zeitpunkt und angeforderte Ressource verarbeitet werden. Die Anwendung verwendet zur Begrenzung missbräuchlicher Anfragen vorübergehend Verbindungskennungen im Arbeitsspeicher. Kontaktinhalte werden nicht in Anwendungsprotokolle geschrieben. Die technische Bereitstellung und Absicherung erfolgen auf Grundlage unseres berechtigten Interesses an einer zuverlässigen und sicheren Website (Art. 6 Abs. 1 lit. f DSGVO).','The website is hosted by Railway Corporation, USA, in the configured EU West region (Amsterdam, Netherlands). Technical connection data such as IP address, time and requested resource may be processed. The application temporarily uses connection identifiers in memory to limit abuse. Contact contents are not written to application logs. Technical operation and security are based on our legitimate interest in a reliable, secure website (Article 6(1)(f) GDPR).')}</p><p>${t(lang,'Der Standort in der EU schließt eine Verarbeitung durch Railway oder dessen Dienstleister außerhalb der EU nicht aus. Informationen zu Railways Datenverarbeitung finden Sie in den','An EU hosting location does not rule out processing by Railway or its providers outside the EU. Information on Railway’s processing is available in its')} <a href="https://railway.com/legal/privacy" target="_blank" rel="noopener noreferrer">${t(lang,'Railway-Datenschutzhinweisen','privacy policy')}</a>.</p>
 <h2>${t(lang,'Cookies, Analyse und externe Inhalte','Cookies, analytics and external content')}</h2><p>${t(lang,'Der neue Website-Code verwendet keine Analyse- oder Werbeskripte, setzt keine eigenen Cookies und lädt keine externen Schriftarten. Formularangaben werden bis zur Übermittlung im geöffneten Browser gehalten.','The new website code uses no analytics or advertising scripts, sets no cookies of its own and loads no external fonts. Form entries remain in the open browser until submission.')}</p>
 <h2>${t(lang,'E-Mail-Verarbeitung und Aufbewahrung','Email processing and retention')}</h2><p>${t(lang,'Für den E-Mail-Versand und das HELLWEG-Postfach verwenden wir STRATO GmbH, Otto-Ostrowski-Straße 7, 10249 Berlin, Deutschland. Nachrichten und Anhänge werden zur Bearbeitung Ihrer Anfrage an HELLWEG übermittelt. Die Aufbewahrungsdauer richtet sich nach der erforderlichen Bearbeitung, einer daraus entstehenden Geschäftsbeziehung und anwendbaren gesetzlichen Aufbewahrungspflichten.','We use STRATO GmbH, Otto-Ostrowski-Straße 7, 10249 Berlin, Germany, for email delivery and the HELLWEG mailbox. Messages and attachments are sent to HELLWEG to handle your enquiry. Retention depends on the necessary handling, any resulting business relationship and applicable statutory retention requirements.')} <a href="https://www.strato.de/datenschutz/" target="_blank" rel="noopener noreferrer">${t(lang,'STRATO-Datenschutzhinweise','STRATO privacy policy')}</a>.</p>
 <h2>${t(lang,'Ihre Rechte','Your rights')}</h2><p>${t(lang,'Nach Maßgabe der DSGVO haben Sie Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung und Datenübertragbarkeit. Soweit die Verarbeitung auf berechtigten Interessen beruht, können Sie aus Gründen Ihrer besonderen Situation widersprechen. Sie können sich zudem bei einer Datenschutzaufsichtsbehörde beschweren. Für die Wahrnehmung Ihrer Rechte schreiben Sie an info@hellweg.eu.','Subject to the GDPR, you have rights of access, rectification, erasure, restriction and data portability. Where processing is based on legitimate interests, you may object on grounds relating to your particular situation. You may also lodge a complaint with a data protection supervisory authority. To exercise your rights, contact info@hellweg.eu.')}</p><p><a href="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32016R0679" target="_blank" rel="noopener noreferrer">${t(lang,'Datenschutz-Grundverordnung','General Data Protection Regulation')}</a></p></section>`;
}

export const pages = { home, products, government, manufacturing, oem, contact, legal, privacy };
